# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.11-slim

# Set environment
ENV PYTHONUNBUFFERED=1
WORKDIR /app

# Copy requirements and install without running scripts
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Default command
CMD ["python3", "-u", "server.py"]
